version: 2.1

aliases:
    - &step_production_dotenv
      run:
          name: Process .env file variables
          command: echo "export $(grep -v '^#' .env | xargs)" >> $BASH_ENV
    - &step_stage_dotenv
      run:
          name: Process .env file variables
          command: echo "export $(grep -v '^#' .env | xargs)" >> $BASH_ENV

jobs:
    build-stg-static:
        docker:
            - image: circleci/node:lts
        steps:
            - checkout
            - *step_stage_dotenv
            - run: echo $TEST

workflows:
    deploy:
        jobs:
            - build-stg-static:
                  filters:
                      branches:
                          only:
                              - test
